create table book(
    id bigint not null generated by default as identity primary key,
	name varchar(100),
	author varchar(100),
	yearOfPublication Integer,
	publishingCompany varchar(100),
	quantity Integer
);